[package]
name = "clicky"
version = "0.1.0"
authors = ["Daniel Prilik <danielprilik@gmail.com>"]
edition = "2018"

[dependencies]
armv4t_emu = "0.1"
bit_field = "0.10.0"
byteorder = "1.3"
crossbeam-channel = "0.4"
gdbstub = { version = "0.1", features = ["std"] }
log = "0.4"
minifb = "0.16"
pretty_env_logger = "0.3"
structopt = "0.3"
termion = "1.5"
thiserror = "1.0"

[profile.dev.package."*"]
opt-level = 3
