name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  clippy_check:
    strategy:
      matrix:
        crate:
          - clicky-core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --package ${{ matrix.crate }}
